### ISSUE TITLE
docker build leads to error module 'pip' has no attribute 'req'

### ISSUE THREAD

**Issue by schlemmge** [FASTGenomics/hello_genomics_calc_py36#7]
Collecting fastgenomics from git+https://github.com/fastgenomics/fastgenomics-py.git@v0.6.0#egg=fastgenomics (from -r /requirements/requirements.txt (line 1))
  Cloning https://github.com/fastgenomics/fastgenomics-py.git (to revision v0.6.0) to /tmp/pip-install-z4up1j34/fastgenomics
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-z4up1j34/fastgenomics/setup.py", line 23, in <module>
        parsed_requirements = pip.req.parse_requirements('requirements.txt', session=pip.download.PipSession())
    AttributeError: module 'pip' has no attribute 'req'

**Comment by Jona77** [comment]
This was an issue with a new version of pip not supporting 'req' anymore. This is not an issue with the newest version of fastgenomics-py. The recommended way of installing fastgenomics-py is now via` pip install fastgenomics`. If an installation via git is desired, fg_py can be build by executing `flit build` and `pip3 install dist/*.whl` in the cloned directory of fastgenomics-py.
